version: '3.5'

services:
  db_auth:
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    image: postgres:14.5-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
